[package]
name = "auto_backlight"
version = "1.0.1"
edition = "2021"
authors = ["Supernovatux <thulashitharan.d@gmail.com>"]
homepage = "https://github.com/Supernovatux/auto_backlight"
repository = "https://github.com/Supernovatux/auto_backlight"
description = "A tool to automatically change brightness based on screen contents"
keywords = ["brightness-control","rust","linux"]
license = "MIT"
include = ["LICENSE", "README.md"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3 
overflow-checks = false
debug = 0
strip = "symbols"

[package.metadata]
depends = ["libxcb","libxrandr","dbus"]

[dependencies]
screenshots={git = "https://github.com/Supernovatux/screenshots-rs",branch = "master"}
clap = { version = "*", features = ["derive"] }
log = "*"
simple_logger = "*"
clap-verbosity-flag = "*"
glob = "*"
ksni = "*"
fast_image_resize = "*"
futures = "*"
futures-timer = "*"